# Importing packages and getting data

In [4]:
import numpy as np
import pandas as pd
import scipy.stats as sc
import scipy.spatial.distance as sp

train_data = pd.read_csv("propublicaTrain.csv")
test_data = pd.read_csv("propublicaTest.csv")
attr = train_data.columns.drop("two_year_recid")

# Helper functions

In [2]:
def bayes_prob(row, train, attr):
    p = 1
    for i in range(len(attr)):
        if row[i+2] in train.index:
            p = p * train.loc[row[i+2]][attr[i]]
        else:
            return 0
    return p

def norm(row, test):
    return np.linalg.norm((row-test)[attr].values, axis=0)

# Maximum Likelihood Estimator

In [5]:
#get data
train_data_m0 = train_data[train_data.two_year_recid==0].fillna(0)
train_data_m1 = train_data[train_data.two_year_recid==1].fillna(0)
test_data_m = test_data.copy()

#drop linearly dependent columns
attr_m = attr[:1]

#fit models
# model_0 = sc.multivariate_normal(mean=np.mean(train_data_m0[attr_m]), cov=np.cov(train_data_m0[attr_m], rowvar=0))
# model_1 = sc.multivariate_normal(mean=np.mean(train_data_m1[attr_m]), cov=np.cov(train_data_m1[attr_m], rowvar=0))
#calculate mahalanobis
sp.mahalanobis(np.mean(train_data_m0[attr_m]), test_data_m.iloc[0], np.cov(train_data_m0[attr_m]))

C:\Users\janep\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: Degrees of freedom <= 0 for slice
  del sys.path[0]
C:\Users\janep\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2326: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
C:\Users\janep\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2326: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

ValueError: shapes (10,) and (2267,2267) not aligned: 10 (dim 0) != 2267 (dim 0)

In [8]:
np.mean(train_data_m0[attr_m])

sex    0.783414
dtype: float64

In [18]:
attr_m = attr[:-1]
sc.multivariate_normal(mean=np.mean(train_data_m0[attr_m]), cov=np.cov(train_data_m0[attr_m], rowvar=0))

# K Nearest Neighbors

In [19]:
train_data_knn = train_data.copy()
test_data_knn = test_data.copy()
test_data_knn["y_1"] = -1
test_data_knn["y_10"] = -1
test_data_knn["y_50"] = -1
test_data_knn["y_200"] = -1
test_data_knn["y_1000"] = -1

for i in range(len(test_data_knn.index)):
    temp = train_data_knn[attr].subtract(test_data_knn.iloc[i][attr])
    train_data_knn["norm"] = temp.apply(np.linalg.norm, axis=1)
    train_data_knn = train_data_knn.sort_values(by="norm", ascending=True)
    test_data_knn["y_1"].iloc[i] = train_data_knn[:1]["two_year_recid"].value_counts().idxmax()
    test_data_knn["y_10"].iloc[i] = train_data_knn[:10]["two_year_recid"].value_counts().idxmax()
    test_data_knn["y_50"].iloc[i] = train_data_knn[:50]["two_year_recid"].value_counts().idxmax()
    test_data_knn["y_200"].iloc[i] = train_data_knn[:200]["two_year_recid"].value_counts().idxmax()
    test_data_knn["y_1000"].iloc[i] = train_data_knn[:1000]["two_year_recid"].value_counts().idxmax()

In [20]:
test_data_knn

,two_year_recid,sex,age,race,juv_fel_count,juv_misd_count,juv_other_count,priors_count,c_charge_degree_F,c_charge_degree_M,y_1,y_10,y_50,y_200,y_1000
0,1,1,27,1,0,0,1,18,1,0,1,1,1,1,1
1,1,0,29,1,0,0,0,11,1,0,0,1,1,1,1
2,1,1,25,1,0,0,1,6,0,1,1,1,1,1,1
3,0,1,26,1,1,0,0,2,1,0,1,0,1,1,0
4,0,0,33,1,0,0,0,2,1,0,0,0,0,0,0
5,0,1,43,0,0,0,0,0,0,1,1,0,0,0,0
6,1,1,22,1,0,0,2,0,1,0,1,1,1,0,0
7,1,1,23,1,0,0,0,2,1,0,0,1,1,1,1
8,1,1,21,1,0,0,0,0,1,0,1,1,0,1,1
9,0,1,31,0,0,0,0,5,1,0,1,1,1,1,0
10,0,1,23,0,0,0,0,1,0,1,0,0,0,0,0
11,0,0,49,1,0,0,0,2,1,0,1,0,0,0,0
12,1,1,24,0,0,0,0,1,1,0,0,1,1,0,0
13,1,1,21,0,0,1,0,2,1,0,0,0,1,1,1
14,1,0,27,1,0,0,0,0,0,1,0,1,0,0,0
15,0,1,29,0,3,0,0,6,1,0,0,1,1,1,1
16,0,1,32,0,0,0,0,1,1,0,0,0,0,0,0
17,1,1,24,0,0,0,0,0,1,0,0,1,0,0,0
18,1,1,41,0,0,0,0,8,1,0,0,1,1,1,0
19,0,1,54,0,0,0,0,4,1,0,1,1,0,0,0
20,1,0,47,0,0,0,0,19,1,0,1,1,1,1,1
21,0,1,26,0,0,0,0,2,0,1,0,0,1,1,0
22,1,1,35,0,0,0,0,16,1,0,1,1,1,1,1
23,1,1,33,0,0,0,0,0,1,0,0,0,0,0,0
24,1,1,33,0,0,0,0,14,1,0,1,1,1,1,1
25,0,1,37,0,0,0,0,3,0,1,0,1,0,0,0
26,1,0,31,1,0,0,0,2,1,0,0,1,0,0,0
27,0,1,31,0,0,0,0,0,0,1,0,0,0,0,0
28,1,1,38,1,0,0,0,5,1,0,0,0,1,0,0
29,0,1,66,1,0,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,1,1,51,0,1,0,0,19,1,0,0,1,1,1,0
1971,1,1,35,0,0,0,0,6,1,0,0,1,1,1,0
1972,1,1,31,1,0,0,1,3,0,1,0,1,1,1,0
1973,0,1,51,0,0,0,0,0,0,1,1,0,0,0,0
1974,0,0,55,1,0,0,0,0,0,1,0,0,0,0,0
1975,1,1,53,1,0,0,0,36,1,0,1,1,1,1,1
1976,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0
1977,1,0,23,0,0,0,0,2,1,0,1,1,1,1,1
1978,0,1,54,0,0,0,0,1,1,0,0,0,0,0,0
1979,1,1,29,0,0,0,0,1,1,0,0,0,0,0,0
1980,0,1,20,1,0,0,0,1,1,0,1,1,1,1,1
1981,0,1,43,0,0,0,0,2,0,1,0,1,0,0,0
1982,0,0,46,0,0,0,0,2,1,0,1,0,0,0,0
1983,0,1,29,0,0,0,0,2,1,0,0,0,0,0,0
1984,0,1,21,0,0,0,0,0,1,0,1,0,1,1,1
1985,1,1,33,1,0,0,0,0,0,1,1,0,0,0,0
1986,0,0,22,0,0,0,0,0,0,1,0,0,0,0,0
1987,0,0,46,1,0,0,0,1,1,0,0,0,0,0,0
1988,0,0,33,1,0,0,0,0,0,1,1,1,0,0,0
1989,0,1,26,0,0,0,0,2,1,0,1,1,0,1,0
1990,1,0,35,0,0,0,0,7,1,0,0,1,1,1,0
1991,0,1,23,0,0,0,0,1,1,0,0,1,1,1,0
1992,0,1,59,0,0,0,0,1,0,1,0,0,0,0,0
1993,0,1,55,0,0,0,0,1,1,0,0,0,0,0,0
1994,1,1,21,1,0,2,1,2,1,0,1,1,1,1,1
1995,0,1,30,0,0,0,0,0,0,1,1,0,0,0,0
1996,1,1,32,0,0,0,0,6,0,1,1,1,1,1,1
1997,1,1,46,1,0,0,0,1,0,1,0,0,0,0,0
1998,0,0,46,1,0,0,0,0,0,1,0,0,0,0,0
1999,1,0,26,1,0,0,0,1,1,0,0,0,0,0,0

In [21]:
test_data_knn["y_1"].iloc[0]=0

In [22]:
print(len(test_data_knn[test_data_knn["two_year_recid"] == test_data_knn["y_1"]].index)/len(test_data_knn.index))
print(len(test_data_knn[test_data_knn["two_year_recid"] == test_data_knn["y_10"]].index)/len(test_data_knn.index))
print(len(test_data_knn[test_data_knn["two_year_recid"] == test_data_knn["y_50"]].index)/len(test_data_knn.index))
print(len(test_data_knn[test_data_knn["two_year_recid"] == test_data_knn["y_200"]].index)/len(test_data_knn.index))
print(len(test_data_knn[test_data_knn["two_year_recid"] == test_data_knn["y_1000"]].index)/len(test_data_knn.index))

0.605
0.6485
0.684
0.6905
0.6785

In [23]:
len(test_data_knn[test_data_knn["two_year_recid"] == test_data_knn["y_50"]].index)/len(test_data_knn.index)

0.684

# Bayes Classifier

In [24]:
#split data 
train_data_b0 = train_data[train_data.two_year_recid==0].apply(pd.Series.value_counts).fillna(0)
train_data_b1 = train_data[train_data.two_year_recid==1].apply(pd.Series.value_counts).fillna(0)

#get counts and adjust for proportion
counts = train_data.two_year_recid.value_counts()
train_data_b0 = train_data_b0/counts[0]
train_data_b1 = train_data_b1/counts[1]
counts = counts/counts.sum()

#get test data
test_data_bayes = test_data.copy()
test_data_bayes["y"] = -1

#classification
for row in test_data.itertuples():
    p_0 = bayes_prob(row, train_data_b0, attr) * counts[0]
    p_1 = bayes_prob(row, train_data_b1, attr) * counts[1]

    #give label
    if p_0 > p_1:
        test_data_bayes["y"].loc[row[0]] = 0
    else:
        test_data_bayes["y"].loc[row[0]] = 1

In [25]:
len(test_data_bayes[test_data_bayes["two_year_recid"] == test_data_bayes["y"]].index)/len(test_data_bayes.index)

0.68

In [26]:
(train_data.iloc[0]-test_data.iloc[0])[attr].values

array([ 0, 37, -1,  0,  0, -1, -5, -1,  1], dtype=int64)